apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: luluplum/db:latest
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "werwerTrip1234"
          - name: MYSQL_DATABASE
            value: "werwerTrip"
          - name: MYSQL_USER
            value: "root"
          - name: MYSQL_PASSWORD
            value: "werwerTrip1234"
        ports:
        - containerPort: 3306